### ISSUE TITLE
Milestone: 0.2 (Visual & Gameplay)

### ISSUE THREAD

**Issue by nixon-voxell** [nixon-voxell/lumina#32]
# Goals

### Global illumination
- [x] #80
- [x] #92

### Player
- [x] #40 
- [x] #50 
- [ ] #78 
- [x] #82
- [x] #103 
- [x] #104
- [x] ~Deterministic weapon firing~
- [x] ~Toggle light~
- [x] #94 

### Game
- [x] #84
- [x] #83
- [x] #81
- [x] #87
- [x] #97
- [x] #100
- [ ] ~#96~ (not in scope)
- [x] #102
- [x] #105
- [x] #114
- [x] #116
- [ ] ~#117~ (not in scope)
- [x] #118

### Playtest
- [x] #101

### Others
- [ ] Update readme screenshot
