### ISSUE TITLE
Milestone: 1.0 (Packaging & Release)

### ISSUE THREAD

**Issue by nixon-voxell** [nixon-voxell/lumina#37]
# Goals

### Trailer
- [ ] Trailer video
- [ ] Trailer thumbnail
- [ ] Trailer gameplay

### Dedicated server setup
- [ ] Purchase a dedicated hosting game server
- [ ] Host game on dedicated server

### Distribution
- [ ] Distribute game on gaming platforms

### Community building (Optional)
- [ ] Create public discord server
- [ ] Organize mini events

**Comment by nixon-voxell** [comment]
This one is 1.0 rather than 0.1.0 haha (#36) @Jian0227
